all:
  children:
    Moscow:
      children:
        el27:
          children:
            bld8fl5:
              hosts:
                172.29.236.1:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld8.floor5
                172.29.236.2:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld8.floor5
                172.29.236.3:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld8.floor5
                172.29.236.4:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld8.floor5
            bld9fl1:
              hosts:
                172.24.10.13:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor1
                172.24.10.14:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor1
                172.24.10.15:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor1
            bld9fl2:
              hosts:
                172.24.10.21:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor2
                172.24.10.23:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor2
                172.24.10.24:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor2
                172.24.10.25:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor2
                172.24.10.26:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor2
                172.24.10.27:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor2
            bld9fl3:
              hosts:
                172.24.10.1:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor3
                172.24.10.32:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor3
                172.24.10.33:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor3
                172.24.10.34:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor3
                172.24.10.35:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor3
                172.24.10.36:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor3
            bld9fl4:
              hosts:
                172.24.10.42:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor4
                172.24.10.43:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor4
                172.24.10.44:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor4
            bld9fl5:
              hosts:
                172.24.10.51:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor5
                172.24.10.52:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor5
                172.24.10.53:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor5
                172.24.10.54:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor5
                172.24.10.55:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor5
            bld9fl6:
              hosts:
                172.24.10.61:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor6
                172.24.10.62:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor6
                172.24.10.63:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor6
                172.24.10.64:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor6
                172.24.10.65:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor6
                172.24.10.66:
                  ansible_network_os: ios
                  ansible_password: ZbszKsx3twa6Rp89Iozc
                  ansible_user: readonly
                  location: Moscow.El27.bld9.floor6
    ios12x:
      hosts:
        172.24.10.15: {}
        172.24.10.24: {}
        172.24.10.27: {}
        172.24.10.43: {}
    ios15x:
      hosts:
        172.24.10.13: {}
        172.24.10.14: {}
        172.24.10.21: {}
        172.24.10.23: {}
        172.24.10.25: {}
        172.24.10.26: {}
        172.24.10.32: {}
        172.24.10.33: {}
        172.24.10.34: {}
        172.24.10.35: {}
        172.24.10.36: {}
        172.24.10.42: {}
        172.24.10.44: {}
        172.24.10.51: {}
        172.24.10.52: {}
        172.24.10.53: {}
        172.24.10.54: {}
        172.24.10.55: {}
        172.24.10.61: {}
        172.24.10.62: {}
        172.24.10.63: {}
        172.24.10.64: {}
        172.24.10.65: {}
        172.24.10.66: {}
    ios16x:
      hosts:
        172.24.10.1: {}
    ungrouped: {}
